### ISSUE TITLE
Change fish tag to avoid confusion with stake.fish

### ISSUE THREAD

**Issue by fkbenjamin** [rated-network/eth2REKT#1]
We had two occurrences in the Lido DAO so far where people mistook slashings of random validators (e.g. see this tweet: https://mobile.twitter.com/eth2REKT/status/1403200337507282946) with slashings of [stake.fish](https://stake.fish/).

I would like to propose changing the name of the "fish" tag to avoid further confusion. To stay in the theme I would suggest a small fish like"starfish", "flounder" or "damselfish".

**Comment by eliasimos** [comment]
thank you @fkbenjamin—this makes a lot of sense. how does “koi” or “koi fish” sit with you?

**Comment by fkbenjamin** [comment]
"koi" or "koi fish" would also be perfectly fine :)

**Comment by eliasimos** [comment]
all done!
